//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsyDocs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse
    {
        public Adresse()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public System.Guid Id { get; set; }
        public string AdresseCivique { get; set; }
        public string CodePostal { get; set; }
        public string Province { get; set; }
        public string Pays { get; set; }
        public string Ville { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
    }
}
