//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsyDocs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public System.Guid Id { get; set; }
        public System.Guid AdresseId { get; set; }
        public System.Guid DossierId { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string NumeroTelephone { get; set; }
        public Sexe Sexe { get; set; }
        public string Courriel { get; set; }
        public Nullable<System.DateTime> DateDeNaissance { get; set; }
        public string Reference { get; set; }
        public string NomAssureur { get; set; }
        public string NumeroTelephoneAssureur { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        public virtual Dossier Dossier { get; set; }
    }
}
