//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsyDocs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dossier
    {
        public Dossier()
        {
            this.Clients = new HashSet<Client>();
            this.Therapies = new HashSet<Therapie>();
        }
    
        public System.Guid Id { get; set; }
        public string Numero { get; set; }
        public System.DateTime Ouverture { get; set; }
        public Nullable<System.DateTime> Fermeture { get; set; }
        public System.Guid UtilisateurId { get; set; }
        public System.Guid ModaliteTraitementId { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<Therapie> Therapies { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual ModaliteTraitement Modalite { get; set; }
    }
}
