//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsyDocs.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PsyDocsContext : DbContext
    {
        public PsyDocsContext()
            : base("name=PsyDocsContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresse> Adresses { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Dossier> Dossiers { get; set; }
        public virtual DbSet<Seance> Seances { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Therapie> Therapies { get; set; }
        public virtual DbSet<TypeDocument> TypeDocuments { get; set; }
        public virtual DbSet<TypeSection> TypeSections { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<ModaliteTraitement> ModaliteTraitements { get; set; }
    }
}
