//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsyDocs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seance
    {
        public System.Guid Id { get; set; }
        public System.Guid TherapieId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Duree { get; set; }
        public string AideMemoire { get; set; }
    
        public virtual Therapie Therapie { get; set; }
    }
}
