//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsyDocs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public System.Guid Id { get; set; }
        public System.Guid DocumentId { get; set; }
        public System.Guid TypeSectionId { get; set; }
        public string Contenu { get; set; }
        public int Position { get; set; }
    
        public virtual TypeSection TypeSection { get; set; }
        public virtual Document Document { get; set; }
    }
}
