//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsyDocs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeSection
    {
        public TypeSection()
        {
            this.Sections = new HashSet<Section>();
            this.TypeDocuments = new HashSet<TypeDocument>();
        }
    
        public System.Guid Id { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<TypeDocument> TypeDocuments { get; set; }
    }
}
