//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsyDocs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeDocument
    {
        public TypeDocument()
        {
            this.TypeSections = new HashSet<TypeSection>();
        }
    
        public System.Guid Id { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<TypeSection> TypeSections { get; set; }
    }
}
